- name: Install zfs.
  ansible.builtin.apt:
    name: "{{ package }}"
    state: present
  loop:
    - zfsutils-linux
    - zfs-dkms
  loop_control:
    loop_var: package

- name: Copy module load config.
  ansible.builtin.copy:
    src: zfs.conf
    dest: /etc/modules-load.d/zfs.conf
    owner: root
    group: root
    mode: "0644"

- name: Load zfs module.
  community.general.modprobe:
    name: zfs
    state: present
