---
- name: Converge
  hosts: all
  vars:
    disks:
      - disk1.img
      - disk2.img
      - disk3.img
  become: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
      changed_when: false
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: true
      when: ansible_distribution == "Archlinux"
      changed_when: false
    - name: Wait for systemd initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        "running" in systemctl_status.stdout or
        "degraded" in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == "systemd"
      changed_when: false
      failed_when: systemctl_status.rc > 1
  tasks:
    - name: Include zfs role.
      ansible.builtin.include_role:
        name: "fkoehler.zfs"
    - name: Create test files for zfs.
      ansible.builtin.command: "truncate --size 1G {{ disk }}"
      args:
        creates: "{{ disk }}"
      loop: "{{ disks }}"
      loop_control:
        loop_var: disk
    - name: Create zpool.
      ansible.builtin.command: "zpool create -f -m /testzpool raidz {{ disks | join(' ') }}"
      args:
        creates: /testzpool
